<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="3" ignored="0" total="5" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="SuiteName" duration-ms="77882" started-at="2018-02-11T01:16:21Z" finished-at="2018-02-11T01:17:39Z">
    <groups>
    </groups>
    <test name="Change Password Test" duration-ms="928" started-at="2018-02-11T01:16:21Z" finished-at="2018-02-11T01:16:22Z">
      <class name="com.selenium.facebook.pom.PageObjectModel_WithPageFactory.testcases.ChangePasswordTest">
        <test-method status="SKIP" signature="changePasswordTest(java.util.Hashtable)[pri:0, instance:com.selenium.facebook.pom.PageObjectModel_WithPageFactory.testcases.ChangePasswordTest@71def8f8]" name="changePasswordTest" duration-ms="60" started-at="2018-02-11T06:46:21Z" data-provider="getData" finished-at="2018-02-11T06:46:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{NewPassword=Shalinikith_5, Username=nikithjain@gmail.com, OldPassword=Shalinikith_1, ExpectedResult=Success, Runmode=Y, Browser=Mozilla}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test as Runmode is N]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test as Runmode is N
	at com.selenium.facebook.pom.PageObjectModel_WithPageFactory.testcases.ChangePasswordTest.changePasswordTest(ChangePasswordTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- changePasswordTest -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.selenium.facebook.pom.PageObjectModel_WithPageFactory.testcases.ChangePasswordTest@71def8f8]" name="quit" is-config="true" duration-ms="783" started-at="2018-02-11T06:46:21Z" finished-at="2018-02-11T06:46:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- com.selenium.facebook.pom.PageObjectModel_WithPageFactory.testcases.ChangePasswordTest -->
    </test> <!-- Change Password Test -->
    <test name="Profile Test" duration-ms="1523" started-at="2018-02-11T01:16:21Z" finished-at="2018-02-11T01:16:23Z">
      <class name="com.selenium.facebook.pom.PageObjectModel_WithPageFactory.testcases.ProfileTest">
        <test-method status="SKIP" signature="testProfile()[pri:0, instance:com.selenium.facebook.pom.PageObjectModel_WithPageFactory.testcases.ProfileTest@67c33749]" name="testProfile" duration-ms="47" started-at="2018-02-11T06:46:21Z" finished-at="2018-02-11T06:46:21Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test as Runmode is  N]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test as Runmode is  N
	at com.selenium.facebook.pom.PageObjectModel_WithPageFactory.testcases.ProfileTest.testProfile(ProfileTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testProfile -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.selenium.facebook.pom.PageObjectModel_WithPageFactory.testcases.ProfileTest@67c33749]" name="quit" is-config="true" duration-ms="1379" started-at="2018-02-11T06:46:21Z" finished-at="2018-02-11T06:46:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- com.selenium.facebook.pom.PageObjectModel_WithPageFactory.testcases.ProfileTest -->
    </test> <!-- Profile Test -->
    <test name="Login Test" duration-ms="75890" started-at="2018-02-11T01:16:21Z" finished-at="2018-02-11T01:17:37Z">
      <class name="com.selenium.facebook.pom.PageObjectModel_WithPageFactory.testcases.LoginTest">
        <test-method status="FAIL" signature="doLogin(java.util.Hashtable)[pri:0, instance:com.selenium.facebook.pom.PageObjectModel_WithPageFactory.testcases.LoginTest@446293d]" name="doLogin" duration-ms="44563" started-at="2018-02-11T06:46:21Z" data-provider="getData" finished-at="2018-02-11T06:47:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Username=nikithjain@gmail.com, ExpectedResult=Success, Password=Shalinikith_5, Runmode=Y, Browser=Mozilla}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failure message]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failure message
	at org.testng.Assert.fail(Assert.java:93)
	at com.selenium.facebook.pom.PageObjectModel_WithPageFactory.testcases.base.BaseTest.reportFailure(BaseTest.java:52)
	at com.selenium.facebook.pom.PageObjectModel_WithPageFactory.testcases.LoginTest.doLogin(LoginTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.selenium.facebook.pom.PageObjectModel_WithPageFactory.testcases.LoginTest@446293d]" name="quit" is-config="true" duration-ms="7882" started-at="2018-02-11T06:47:06Z" finished-at="2018-02-11T06:47:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method status="FAIL" signature="doLogin(java.util.Hashtable)[pri:0, instance:com.selenium.facebook.pom.PageObjectModel_WithPageFactory.testcases.LoginTest@446293d]" name="doLogin" duration-ms="15680" started-at="2018-02-11T06:47:14Z" data-provider="getData" finished-at="2018-02-11T06:47:29Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Username=nikithjain@gmail.com, ExpectedResult=Success, Password=xxxxxxx, Runmode=Y, Browser=Chrome}]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.WebDriverException">
            <message>
              <![CDATA[unknown error: cannot get automation extension
from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html
  (Session info: chrome=64.0.3282.140)
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 10.06 seconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'VASANTKN1', ip: '16.169.1.42', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_111'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.29.461591 (62ebf098771772160f391d75e589dc567915b233), userDataDir=C:\Users\vasantkn\AppData\Local\Temp\scoped_dir15264_24727}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=64.0.3282.140, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: 21764f6a996cb6dd4f20fbf06524fe19]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.WebDriverException: unknown error: cannot get automation extension
from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html
  (Session info: chrome=64.0.3282.140)
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 10.06 seconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'VASANTKN1', ip: '16.169.1.42', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_111'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.29.461591 (62ebf098771772160f391d75e589dc567915b233), userDataDir=C:\Users\vasantkn\AppData\Local\Temp\scoped_dir15264_24727}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=64.0.3282.140, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: 21764f6a996cb6dd4f20fbf06524fe19
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:671)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:694)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteWindow.maximize(RemoteWebDriver.java:925)
	at com.selenium.facebook.pom.PageObjectModel_WithPageFactory.testcases.base.BaseTest.init(BaseTest.java:45)
	at com.selenium.facebook.pom.PageObjectModel_WithPageFactory.testcases.LoginTest.doLogin(LoginTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.WebDriverException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.selenium.facebook.pom.PageObjectModel_WithPageFactory.testcases.LoginTest@446293d]" name="quit" is-config="true" duration-ms="7675" started-at="2018-02-11T06:47:29Z" finished-at="2018-02-11T06:47:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- com.selenium.facebook.pom.PageObjectModel_WithPageFactory.testcases.LoginTest -->
    </test> <!-- Login Test -->
    <test name="Friends Test" duration-ms="77854" started-at="2018-02-11T01:16:21Z" finished-at="2018-02-11T01:17:39Z">
      <class name="com.selenium.facebook.pom.PageObjectModel_WithPageFactory.testcases.FriendsTest">
        <test-method status="FAIL" signature="doFriendsTest(java.util.Hashtable)[pri:0, instance:com.selenium.facebook.pom.PageObjectModel_WithPageFactory.testcases.FriendsTest@20ccf40b]" name="doFriendsTest" duration-ms="70389" started-at="2018-02-11T06:46:21Z" data-provider="getData" finished-at="2018-02-11T06:47:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{FriendName=Sujay, Runmode=Y, Browser=Mozilla}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Could not login]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Could not login
	at org.testng.Assert.fail(Assert.java:93)
	at com.selenium.facebook.pom.PageObjectModel_WithPageFactory.testcases.base.BaseTest.reportFailure(BaseTest.java:52)
	at com.selenium.facebook.pom.PageObjectModel_WithPageFactory.testcases.FriendsTest.doFriendsTest(FriendsTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doFriendsTest -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.selenium.facebook.pom.PageObjectModel_WithPageFactory.testcases.FriendsTest@20ccf40b]" name="quit" is-config="true" duration-ms="7377" started-at="2018-02-11T06:47:32Z" finished-at="2018-02-11T06:47:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- com.selenium.facebook.pom.PageObjectModel_WithPageFactory.testcases.FriendsTest -->
    </test> <!-- Friends Test -->
  </suite> <!-- SuiteName -->
</testng-results>
